x=int(input('enter the first number '))
y=int(input('enter the second number '))
print('Addition of',x,'and',y,'is',(x+y))
print('Subtraction of',x,'and',y,'is',(x-y))
print('Division of',x,'and',y,'is', int((x/y)))
print('Remainder after performing division of',x,'and',y,'is',(x%y))
print('Multiplication of',x,'and',y,'is',(x*y))